# -*- coding: utf-8 -*-
"""stitt_fair_tiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nX_z70stm6t2JnlaZWE3XhkeYKO8BlcM
"""

!pip install jaxopt blue_sampler

import numpy as np


# ------------------------------------------------------------
# Aire spécialisée quadrilatère
# ------------------------------------------------------------

def quad_signed_area(q):
    x0, y0 = q[..., 0, 0], q[..., 0, 1]
    x1, y1 = q[..., 1, 0], q[..., 1, 1]
    x2, y2 = q[..., 2, 0], q[..., 2, 1]
    x3, y3 = q[..., 3, 0], q[..., 3, 1]

    return 0.5 * (
        x0 * y1 - x1 * y0
        + x1 * y2 - x2 * y1
        + x2 * y3 - x3 * y2
        + x3 * y0 - x0 * y3
    )


def area4(P0, P1, P2, P3):
    return 0.5 * (
        P0[..., 0] * P1[..., 1] - P1[..., 0] * P0[..., 1]
        + P1[..., 0] * P2[..., 1] - P2[..., 0] * P1[..., 1]
        + P2[..., 0] * P3[..., 1] - P3[..., 0] * P2[..., 1]
        + P3[..., 0] * P0[..., 1] - P0[..., 0] * P3[..., 1]
    )


# ------------------------------------------------------------
# Split
# ------------------------------------------------------------

def _attempt(quads, pool, rng, n_iter=40, eps=1e-9):

    B = quads.shape[0]

    A = quads[:, 0]
    Bv = quads[:, 1]
    C = quads[:, 2]
    D = quads[:, 3]

    total_area = quad_signed_area(quads)
    target = (total_area * 0.5)[:, None]

    theta = rng.uniform(0.0, np.pi, size=(B, pool))

    sin_t = np.sin(theta)
    cos_t = np.cos(theta)

    nx = -sin_t
    ny = cos_t

    # --------------------------------------------------------
    # projections
    # --------------------------------------------------------

    def lvl(P):
        return (
            P[:, None, 0] * nx
            + P[:, None, 1] * ny
        )

    hA = lvl(A)
    hB = lvl(Bv)
    hC = lvl(C)
    hD = lvl(D)

    h = np.stack((hA, hB, hC, hD), axis=-1)

    h_sorted = np.sort(h, axis=-1)

    l1 = h_sorted[..., 1]
    l2 = h_sorted[..., 2]

    is_bottom2 = h <= l1[..., None]

    cross_DA_BC = (
        (is_bottom2[..., 0] & is_bottom2[..., 1])
        |
        (is_bottom2[..., 2] & is_bottom2[..., 3])
    )

    # --------------------------------------------------------
    # interpolation
    # --------------------------------------------------------

    def edge_point(V1, V2, h1, h2, t):

        denom = h2 - h1
        denom = np.where(np.abs(denom) < eps, eps, denom)

        alpha = (t - h1) / denom

        return (
            V1[:, None, :]
            + alpha[..., None] * (V2 - V1)[:, None, :]
        )

    # broadcasts réutilisés
    Ab = np.broadcast_to(A[:, None, :], (B, pool, 2))
    Bb = np.broadcast_to(Bv[:, None, :], (B, pool, 2))
    Cb = np.broadcast_to(C[:, None, :], (B, pool, 2))
    Db = np.broadcast_to(D[:, None, :], (B, pool, 2))

    def area_at(t):

        P_AB = edge_point(A, Bv, hA, hB, t)
        P_BC = edge_point(Bv, C, hB, hC, t)
        P_CD = edge_point(C, D, hC, hD, t)
        P_DA = edge_point(D, A, hD, hA, t)

        area_DA_BC = area4(
            Ab,
            Bb,
            P_BC,
            P_DA,
        )

        area_AB_CD = area4(
            P_AB,
            Bb,
            Cb,
            P_CD,
        )

        area = np.where(
            cross_DA_BC,
            area_DA_BC,
            area_AB_CD,
        )

        return area, (P_AB, P_BC, P_CD, P_DA)

    # --------------------------------------------------------
    # recherche intervalle
    # --------------------------------------------------------

    area_l1, _ = area_at(l1)
    area_l2, _ = area_at(l2)

    f_l1 = area_l1 - target
    f_l2 = area_l2 - target

    pool_ok = (f_l1 * f_l2) <= 0

    # --------------------------------------------------------
    # dichotomie
    # --------------------------------------------------------

    lo = l1.copy()
    hi = l2.copy()

    f_lo = f_l1.copy()

    mid = np.empty_like(lo)

    for _ in range(n_iter):

        np.add(lo, hi, out=mid)
        mid *= 0.5

        f_mid, _ = area_at(mid)
        f_mid -= target

        same_sign = np.signbit(f_mid) == np.signbit(f_lo)

        lo = np.where(same_sign, mid, lo)
        hi = np.where(same_sign, hi, mid)

        f_lo = np.where(same_sign, f_mid, f_lo)

    t_star = 0.5 * (lo + hi)

    # --------------------------------------------------------
    # géométrie finale
    # --------------------------------------------------------

    _, (P_AB, P_BC, P_CD, P_DA) = area_at(t_star)

    piece1_DABC = np.stack(
        (Ab, Bb, P_BC, P_DA),
        axis=-2,
    )

    piece2_DABC = np.stack(
        (P_BC, Cb, Db, P_DA),
        axis=-2,
    )

    piece1_ABCD = np.stack(
        (P_AB, Bb, Cb, P_CD),
        axis=-2,
    )

    piece2_ABCD = np.stack(
        (Ab, P_AB, P_CD, Db),
        axis=-2,
    )

    mask = cross_DA_BC[..., None, None]

    piece1 = np.where(mask, piece1_DABC, piece1_ABCD)
    piece2 = np.where(mask, piece2_DABC, piece2_ABCD)

    ok = np.any(pool_ok, axis=1)

    idx_sel = np.argmax(pool_ok, axis=1)

    piece1_sel = np.take_along_axis(
        piece1,
        idx_sel[:, None, None, None],
        axis=1,
    )[:, 0]

    piece2_sel = np.take_along_axis(
        piece2,
        idx_sel[:, None, None, None],
        axis=1,
    )[:, 0]

    return piece1_sel, piece2_sel, ok


def fair_random_split(
    quads,
    pool=30,
    n_iter=40,
    rng=None,
    max_retries=5,
    growth=4,
):

    rng = np.random.default_rng() if rng is None else rng

    B = quads.shape[0]

    piece1 = np.empty((B, 4, 2), dtype=quads.dtype)
    piece2 = np.empty((B, 4, 2), dtype=quads.dtype)

    resolved = np.zeros(B, dtype=bool)

    remaining_idx = np.arange(B)

    cur_pool = pool

    for _ in range(max_retries + 1):

        if len(remaining_idx) == 0:
            break

        p1, p2, ok = _attempt(
            quads[remaining_idx],
            cur_pool,
            rng,
            n_iter=n_iter,
        )

        good = remaining_idx[ok]

        piece1[good] = p1[ok]
        piece2[good] = p2[ok]

        resolved[good] = True

        remaining_idx = remaining_idx[~ok]

        cur_pool *= growth

    if len(remaining_idx):

        raise RuntimeError(
            f"no fair quad/quad split found for "
            f"{len(remaining_idx)} polygon(s)"
        )

    return np.concatenate(
        (piece1, piece2),
        axis=0,
    )

import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng(3)
quad = np.array([[[0,0],[2,0.3],[1.7,1.6],[0.2,1.4]]], dtype=float)

cur = quad

for _ in range(3):
    fig, axes = plt.subplots(1, 4, figsize=(16,4))
    for ax, gen in zip(axes, range(4)):
        for q in cur:
            poly = np.vstack([q, q[0]])
            ax.plot(poly[:,0], poly[:,1], '-o', ms=3)
            ax.fill(q[:,0], q[:,1], alpha=0.25)
        ax.set_title(f"gen {gen} (n={len(cur)})")
        ax.set_aspect('equal')
        if gen < 3:
            cur = fair_random_split(cur, pool=30, rng=rng)

    plt.tight_layout()
    plt.show()

import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng(3)
quad = np.array([[[0,0],[2,0.3],[1.7,1.6],[0.2,1.4]]], dtype=float)

cur = quad

for _ in range(10):
    cur = fair_random_split(cur, pool=30, rng=rng)
    print(len(cur))

import torch

def sample_quad(quad, N):
    """
    quad: (B,4,2)
    return: (B,N,2)
    """

    B = quad.shape[0]
    u = torch.rand(B, N, 2, device=quad.device)

    q0, q1, q2, q3 = quad[:,0], quad[:,1], quad[:,2], quad[:,3]

    pts = (
        (1-u[...,0:1])*(1-u[...,1:2])*q0[:,None]
        + u[...,0:1]*(1-u[...,1:2])*q1[:,None]
        + u[...,0:1]*u[...,1:2]*q2[:,None]
        + (1-u[...,0:1])*u[...,1:2]*q3[:,None]
    )

    return pts

from geomloss import SamplesLoss

sinkhorn = SamplesLoss(
    loss="sinkhorn",
    p=2,
    blur=0.05,
)

def optimize_points(quad, N=50, steps=200, lr=0.1):

    device = quad.device
    B = quad.shape[0]

    # target distribution = vrai quad
    target = sample_quad(quad, N)

    # init points dans bounding box
    minb = quad.min(dim=1, keepdim=True).values
    maxb = quad.max(dim=1, keepdim=True).values

    x = torch.rand(B, N, 2, device=device)
    x = minb + x * (maxb - minb)

    x.requires_grad_(True)

    opt = torch.optim.Adam([x], lr=lr)

    for i in range(steps):
        opt.zero_grad()

        loss = sinkhorn(x, target)

        loss.backward()
        opt.step()

        if i % 20 == 0:
            print(f"step {i} | loss = {loss.item():.6f}")

    return x.detach()

import jax
import jax.numpy as jnp
from jaxopt import LBFGS

jax.config.update("jax_enable_x64", True)


# ============================================================
# Triangle moments
# ============================================================

def triangle_moments(v0, v1, v2, P, nq=8):
    """
    Moments géométriques exacts (à précision quadrature)
    d'un triangle.

    Retour:
        dict[(i,j)] -> (B,)
    """

    B = v0.shape[0]

    # Gauss-Legendre sur [0,1]
    xg, wg = jnp.polynomial.legendre.leggauss(nq)

    u = 0.5 * (xg + 1.0)
    wu = 0.5 * wg

    uu, vv = jnp.meshgrid(u, u, indexing="ij")
    wu2, wv2 = jnp.meshgrid(wu, wu, indexing="ij")

    uu = uu.reshape(-1)
    vv = vv.reshape(-1)

    weights = (wu2 * wv2).reshape(-1)

    # transformation carré -> triangle
    r = uu
    s = (1.0 - uu) * vv

    jac_ref = (1.0 - uu)

    p = (
        v0[:, None, :]
        + r[None, :, None] * (v1 - v0)[:, None, :]
        + s[None, :, None] * (v2 - v0)[:, None, :]
    )

    x = p[..., 0]
    y = p[..., 1]

    J = jnp.abs(
        (v1[:, 0] - v0[:, 0]) * (v2[:, 1] - v0[:, 1])
        - (v1[:, 1] - v0[:, 1]) * (v2[:, 0] - v0[:, 0])
    )

    det = J[:, None] * jac_ref[None, :]

    moments = {}

    for order in range(P + 1):
        for i in range(order + 1):
            j = order - i

            val = jnp.sum(
                weights[None, :]
                * det
                * (x ** i)
                * (y ** j),
                axis=1,
            )

            moments[(i, j)] = val

    return moments


# ============================================================
# Quad moments
# ============================================================

def quad_moments(quad, P):
    """
    quad : (B,4,2)
    """

    q0 = quad[:, 0]
    q1 = quad[:, 1]
    q2 = quad[:, 2]
    q3 = quad[:, 3]

    m1 = triangle_moments(q0, q1, q2, P)
    m2 = triangle_moments(q0, q2, q3, P)

    return {
        k: m1[k] + m2[k]
        for k in m1
    }


# ============================================================
# Bilinear mapping square -> quad
# ============================================================

def bilinear_map(quad, uv):
    """
    quad : (B,4,2)
    uv   : (B,N,2)
    """

    u = uv[..., 0:1]
    v = uv[..., 1:2]

    q0 = quad[:, None, 0]
    q1 = quad[:, None, 1]
    q2 = quad[:, None, 2]
    q3 = quad[:, None, 3]

    return (
        (1-u)*(1-v)*q0
        + u*(1-v)*q1
        + u*v*q2
        + (1-u)*v*q3
    )


# ============================================================
# Sampler
# ============================================================

def sample_as_jax(
    quad,
    N,
    P,
    max_iter=200,
):
    B = quad.shape[0]

    target = quad_moments(quad, P)

    area = target[(0, 0)]

    key = jax.random.PRNGKey(0)

    uv0 = jax.random.uniform(
        key,
        (B, N, 2),
        minval=0.05,
        maxval=0.95,
    )

    def loss_fn(z):

        uv = jax.nn.sigmoid(z)

        pts = bilinear_map(quad, uv)

        x = pts[..., 0]
        y = pts[..., 1]

        loss = 0.0

        for order in range(P + 1):
            for i in range(order + 1):
                j = order - i

                discrete = (
                    area / N
                    * jnp.sum(
                        x**i * y**j,
                        axis=1,
                    )
                )

                tgt = target[(i, j)]

                rel = (
                    (discrete - tgt)
                    / (jnp.abs(tgt) + 1e-12)
                )

                loss += jnp.mean(rel**2)

        return loss

    z0 = jnp.log(uv0) - jnp.log1p(-uv0)

    solver = LBFGS(
        fun=loss_fn,
        maxiter=max_iter,
        tol=1e-10,
    )

    res = solver.run(z0)

    uv = jax.nn.sigmoid(res.params)

    return bilinear_map(quad, uv)

# génération
x = sample_as_jax(
    cur,
    N=15,
    P=4,
    max_iter=200,
)

print(x.shape)

print(cur.shape)



x = np.array(points_vises).reshape(-1, 2)

xshow = x[(x > 0.4).all(axis = -1) & (x < 1.3).all(axis = -1)]
plt.figure(figsize=(8, 8))
plt.scatter(xshow[:, 0], xshow[:, 1], color = "black")
plt.axis("off")
plt.show()

!pip install blue_sampler

xshow = xshow - xshow.min()

xshow = xshow / xshow.max()

import blue_sampler as blue

blue.plot_structure_factor(xshow, resolution = 10)