#!/usr/bin/env python
"""Build a new randomised (N, D) hyperuniform point cloud from the downloaded database.

Usage
-----
    python new_data.py --dim 2 --npoints 1024 --chi 43 --seed 42
    python new_data.py --dim 20 --npoints 2**20 --chi 30 --seed 0   (N may be '2**k')

Pipeline
--------
1. Base cloud   : N_base = min(N, 2**17) points, read from the downloaded .h5 files
                  (`<data>/chi{chi}/D{D_src}/N{i}_D{D_src}.h5`).
2. Projection   : if D is not stored, keep D randomly chosen coordinates of the
                  smallest stored dimension >= D (23 or 32). Keeping coordinates
                  preserves periodicity and stealthiness on the kept axes.
3. Tiling       : if N > 2**17, multiply the number of points by 2**K (see `tile`).
4. Randomisation: random shift x -> (x - s) mod 1, random flips x_d -> 1 - x_d,
                  random axis swap.

Tiling (K = log2 of the multiplication factor, P = D // 2 pairs of dimensions)
------------------------------------------------------------------------------
For a pair of axes (a, b), the 2D cloud is periodic, so we may "cut a slice" of the
infinite periodic pattern along the lattice generated by (1, 1) and (1, -1): points
(u, v) -> ((u + v)/2, (u - v)/2) mod 1, for u = x_a + {0, 1}. This is a 45 degree
rotation (and a 1/sqrt(2) rescaling) of the pattern: it doubles the number of points
and keeps periodicity on the unit cube. The structure factor is preserved up to the
factor N_t / N, as for ordinary tiling.
  * K <= P         : one such step on K randomly chosen pairs.
  * P < K <= 2P    : the same, twice (the second pass uses pairs shifted by one axis).
  * K > 2P         : first pure tiling with 2**k copies per axis (k = K // D, which
                     multiplies N by 2**(k*D)), then the steps above on the remainder.
Slight loss of isotropy, without consequence.
"""
import argparse
import sys
from pathlib import Path

import h5py
import numpy as np

AVAILABLE_DIMS = list(range(2, 17)) + [23, 32]
AVAILABLE_CHIS = [30, 43]  # chi = 0.30 and chi = 0.43

MIN_LOG2 = 10          # smallest N stored: 2**10 = 1024
MAX_BASE_LOG2 = 17     # largest N stored:  2**17 = 131072


def read_base(data_dir, chi, log2n, D_src):
    """Read the stored (2**log2n, D_src) float32 cloud for this chi."""
    path = Path(data_dir) / f"chi{chi}" / f"D{D_src}" / f"N{log2n}_D{D_src}.h5"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run: python load_data.py --dim {D_src} --chi {chi}")
    with h5py.File(path, "r") as f:
        return f["points"][()]


def pure_tile(X, k):
    """2**k copies per axis: X (n, D) -> (n * 2**(k*D), D), still periodic on [0,1)^D."""
    n, D = X.shape
    r = 2 ** k
    grid = np.stack(np.meshgrid(*[np.arange(r)] * D, indexing="ij"), -1).reshape(-1, D)
    out = np.empty((len(grid) * n, D), dtype=np.float32)
    for i, t in enumerate(grid):
        out[i * n:(i + 1) * n] = (X.astype(np.float64) + t) / r
    return out


def rotate_pair(X, a, b):
    """Double the cloud with the 45-degree slice on axes (a, b). Returns a new array."""
    n = len(X)
    Y = np.concatenate([X, X])
    u = Y[:, a].astype(np.float64)
    v = Y[:, b].astype(np.float64)
    u[n:] += 1.0                      # second coset representative of Z^2 / M Z^2
    Y[:, a] = np.mod((u + v) / 2, 1.0)
    Y[:, b] = np.mod((u - v) / 2, 1.0)
    return Y


def tile(X, K, rng = None):
    """Multiply the number of points of X by 2**K by tiling it.
    One can  choose the random generator by passing one e.g. as
        rng = numpy.random.default_rng(42)
    """
    if rng is None:
        rng = np.random.default_rng(42)
    D = X.shape[1]
    P = D // 2
    k = K // D if K > 2 * P else 0
    if k:
        X = pure_tile(X, k)
    rem = K - k * D
    counts = (min(rem, P), rem - min(rem, P))    # first pass, second pass

    order = rng.permutation(D)
    for count, ordr in zip(counts, (order, np.roll(order, -1))):
        pairs = ordr[:2 * P].reshape(P, 2)
        for j in rng.choice(P, size=count, replace=False):
            X = rotate_pair(X, *pairs[j])
    return X


def new_data(N, D, chi, seed, data_dir="data"):
    """Return a randomised (N, D) float32 point cloud on [0,1)^D."""
    if N < 2 ** MIN_LOG2 or N & (N - 1):
        raise ValueError(f"N must be a power of 2 >= {2 ** MIN_LOG2}, got {N}")
    if not 2 <= D <= AVAILABLE_DIMS[-1]:
        raise ValueError(f"D must be in [2, {AVAILABLE_DIMS[-1]}], got {D}")
    if chi not in AVAILABLE_CHIS:
        raise ValueError(f"chi must be in {AVAILABLE_CHIS}, got {chi}")

    rng = np.random.default_rng(seed)
    log2n = N.bit_length() - 1
    base_log2 = min(log2n, MAX_BASE_LOG2)
    D_src = next(d for d in AVAILABLE_DIMS if d >= D)

    X = read_base(data_dir, chi, base_log2, D_src)
    if D_src != D:                                   # random projection on D coordinates
        X = X[:, rng.permutation(D_src)[:D]]
    X = tile(X, log2n - base_log2, rng)

    shift = rng.random(D)
    flip = rng.random(D) < 0.5
    axis = rng.permutation(D)

    X = np.mod(X.astype(np.float64) - shift, 1.0)
    X[:, flip] = 1.0 - X[:, flip]
    X = X[:, axis]
    return np.mod(X.astype(np.float32), 1.0)         # float32 rounding can give 1.0


def parse_int(s):
    """Accepts '1024', '2**10', '1<<10'."""
    s = s.replace(" ", "")
    if "**" in s:
        a, b = s.split("**")
        return int(a) ** int(b)
    if "<<" in s:
        a, b = s.split("<<")
        return int(a) << int(b)
    return int(s)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dim", type=int, required=True, help="dimension D (2..32)")
    p.add_argument("--npoints", type=parse_int, required=True,
                   help="number of points N (power of 2, >= 1024; '2**20' accepted)")
    p.add_argument("--chi", type=int, required=True, choices=AVAILABLE_CHIS,
                   help="30 (chi=0.30) or 43 (chi=0.43)")
    p.add_argument("--seed", type=int, default=0, help="random seed (default 0)")
    p.add_argument("--data", default="data", help="directory given to load_data.py")
    p.add_argument("--out", default=None,
                   help="output .npy file (default: new_data/N{N}_D{D}_chi{chi}_seed{seed}.npy)")
    args = p.parse_args()

    try:
        X = new_data(args.npoints, args.dim, args.chi, args.seed, args.data)
    except (ValueError, FileNotFoundError) as e:
        sys.exit(f"error: {e}")

    out = Path(args.out or
               f"new_data/N{args.npoints}_D{args.dim}_chi{args.chi}_seed{args.seed}.npy")
    out.parent.mkdir(parents=True, exist_ok=True)
    np.save(out, X)
    print(f"wrote {out}: shape {X.shape}.")


if __name__ == "__main__":
    main()
